name: Build and run tests
on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main
      - 'apl-fy[0-9][0-9]'
  pull_request: {} # any target

jobs:
  unit-test:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-24.04', 'centos-9']
    name: Unit Test (os=${{matrix.os}})
    runs-on: ${{ matrix.os == 'centos-9' && 'ubuntu-24.04' || matrix.os }}
    container: ${{ matrix.os == 'centos-9' && 'quay.io/centos/centos:stream9' || null }}
    permissions:
      contents: read
      actions: write
    steps:
      - name: Set up OS
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
              cmake ninja-build ruby build-essential \
              libssl-dev \
              valgrind gcovr xmlstarlet
      - name: Set up OS
        if: startsWith(matrix.os, 'centos')
        run: |
          dnf config-manager --set-enabled crb
          dnf install -y epel-release
          dnf install -y \
              git rsync \
              cmake ninja-build \
              ruby pkg-config gcc gcc-c++ ccache patch \
              openssl-devel \
              valgrind xmlstarlet python3-pip
          pip3 install gcovr
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true
      - name: Dependencies
        run: ./deps.sh
      - name: Prep
        run: ./prep.sh -DBUILD_DOCS_API=OFF -DBUILD_DOCS_MAN=OFF -DBUILD_TESTING=ON
      - name: Build
        run: ./build.sh
      - name: Test
        run: ./build.sh check
      - name: Collect coverage
        run: ./build.sh coverage
      - name: Archive coverage
        uses: actions/upload-artifact@v4
        with:
          name: ${{github.job}}-${{matrix.os}}-coverage
          path: build/default/coverage*
      - name: Report coverage
        run: |
          SRC_COV_PERC=$(xmlstarlet sel -t -v 'floor(/coverage/packages/package[@name="src"]/@line-rate * 100)' -n build/default/coverage-xml.xml)
          echo "Source coverage: ${SRC_COV_PERC}%" >> $GITHUB_STEP_SUMMARY

  mock-bpa-test:
    name: Mock BPA Test (os=ubunntu-24.04)
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      actions: write
    steps:
      - name: Set up OS
        run: >
          sudo apt-get update && sudo apt-get install -y
          cmake ninja-build ruby build-essential
          libssl-dev
          valgrind gcovr xmlstarlet
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true
      - name: Dependencies
        run: ./deps.sh
      - name: Prep
        run: ./prep.sh -DBUILD_DOCS_API=OFF -DBUILD_DOCS_MAN=OFF -DBUILD_TESTING=ON
      - name: Build
        run: ./build.sh
      - name: Install
        run: ./build.sh install
      - name: Check symbols
        run: echo ./check_symbols.py bsl #FIXME replace
      - name: Test Prep
        run: |
          sudo apt-get update && sudo apt-get install -y \
          python3 python3-pip
          pip3 install --upgrade pip
          pip3 install -r mock-bpa-test/requirements.txt
      - name: Test
        run: python3 -m pytest mock-bpa-test --capture=no --log-cli-level=debug
      - name: Collect coverage
        run: ./build.sh coverage
      - name: Archive coverage
        uses: actions/upload-artifact@v4
        with:
          name: mock-bpa-test-coverage
          path: build/default/coverage*
      - name: Report coverage
        run: |
          SRC_COV_PERC=$(xmlstarlet sel -t -v 'floor(/coverage/packages/package[@name="src"]/@line-rate * 100)' -n build/default/coverage-xml.xml)
          echo "Source coverage: ${SRC_COV_PERC}%" >> $GITHUB_STEP_SUMMARY
