name: Build and run tests
on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
    - main
  pull_request: {} # any target

jobs:
  unit-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up OS
        run: >
          sudo apt-get update && sudo apt-get install -y
          cmake ninja-build ruby build-essential
          libssl-dev
          valgrind gcovr xmlstarlet
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true
      - name: Prep
        run: ./deps.sh && ./prep.sh -DBUILD_DOCS=OFF
      - name: Build
        run: ./build.sh
      - name: Test
        run: ./build.sh check
      - name: Collect coverage
        run: ./build.sh coverage
      - name: Archive coverage
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-coverage
          path: build/default/coverage*
      - name: Report coverage
        run: |
          SRC_COV_PERC=$(xmlstarlet sel -t -v 'floor(/coverage/packages/package[@name="src"]/@line-rate * 100)' -n build/default/coverage-xml.xml)
          echo "Source coverage: ${SRC_COV_PERC}%" >> $GITHUB_STEP_SUMMARY

  mock-bpa-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up OS
        run: >
          sudo apt-get update && sudo apt-get install -y
          cmake ninja-build ruby build-essential
          libssl-dev
          valgrind gcovr xmlstarlet
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true
      - name: Prep
        run: ./deps.sh && ./prep.sh -DBUILD_DOCS=OFF
      - name: Build
        run: ./build.sh
      - name: Install
        run: ./build.sh install
      - name: Test Prep
        run: |
          sudo apt-get update && sudo apt-get install -y \
          python3 python3-pip
          pip3 install --upgrade pip
          pip3 install -r mock-bpa-test/requirements.txt
      - name: Test
        run: python3 -m pytest mock-bpa-test --capture=no --log-cli-level=debug
      - name: Collect coverage
        run: ./build.sh coverage
      - name: Archive coverage
        uses: actions/upload-artifact@v4
        with:
          name: mock-bpa-test-coverage
          path: build/default/coverage*
      - name: Report coverage
        run: |
          SRC_COV_PERC=$(xmlstarlet sel -t -v 'floor(/coverage/packages/package[@name="src"]/@line-rate * 100)' -n build/default/coverage-xml.xml)
          echo "Source coverage: ${SRC_COV_PERC}%" >> $GITHUB_STEP_SUMMARY
