##
## Copyright (c) 2025 The Johns Hopkins University Applied Physics
## Laboratory LLC.
##
## This file is part of the Bundle Protocol Security Library (BSL).
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##     http://www.apache.org/licenses/LICENSE-2.0
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## This work was performed for the Jet Propulsion Laboratory, California
## Institute of Technology, sponsored by the United States Government under
## the prime contract 80NM0018D0004 between the Caltech and NASA under
## subcontract 1700763.
##
name: Packages
on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
    - main
  pull_request: {} # any target

jobs:
  rpm:
    runs-on: ubuntu-22.04
    container: quay.io/centos/centos:stream9
    permissions:
      contents: read
      actions: write
    steps:
      - name: Set up OS
        run: |
          dnf config-manager --set-enabled crb
          dnf install -y epel-release
          dnf install -y \
              rsync cmake git ninja-build gcc ruby \
              openssl-devel jansson-devel \
              doxygen graphviz plantuml texlive-bibtex \
              asciidoctor \
              rpm-build rpmlint
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Prep
        run: ./build.sh prep -DBUILD_LIB=OFF -DBUILD_TESTING=OFF -DBUILD_DOCS_API=OFF -DBUILD_DOCS_MAN=OFF -DBUILD_PACKAGE=ON
      - name: Build
        run: |
          ./build.sh rpm-build
      - name: rpmlint Results
        if: always()
        run: |
          echo "## rpmlint results:" >> $GITHUB_STEP_SUMMARY
          echo >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cat build/default/pkg/rpmbuild/rpmlint.txt >> $GITHUB_STEP_SUMMARY
          echo >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: bsl-rpm
          path: |
            build/default/pkg/rpmbuild/SRPMS
            build/default/pkg/rpmbuild/RPMS
            build/default/pkg/rpmbuild/rpmlint.txt
          retention-days: 1
