##
## Copyright (c) 2025-2026 The Johns Hopkins University Applied Physics
## Laboratory LLC.
##
## This file is part of the Bundle Protocol Security Library (BSL).
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##     http://www.apache.org/licenses/LICENSE-2.0
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## This work was performed for the Jet Propulsion Laboratory, California
## Institute of Technology, sponsored by the United States Government under
## the prime contract 80NM0018D0004 between the Caltech and NASA under
## subcontract 1700763.
##
name: SonarQube
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-24.04
    steps:
      - name: Set up OS
        env:
          PIP_BREAK_SYSTEM_PACKAGES: 1
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              cmake ninja-build ruby build-essential \
              libssl-dev libjansson-dev \
              xmlstarlet \
              python3 python3-pip python3-wheel
          pip3 install gcovr
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          submodules: recursive
      - name: Dependencies
        run: ./build.sh deps
      - name: Prep
        run: >
          ./build.sh prep
          -DBUILD_DOCS_API=OFF -DBUILD_DOCS_MAN=OFF
          -DBUILD_UNITTEST=ON
          -DTEST_MEMCHECK=OFF -DBUILD_COVERAGE=ON
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - name: Build
        run: ./build.sh
      - name: Install
        run: ./build.sh install
      - name: Unit Test
        run: ./build.sh check --output-junit testresults.xml || true
      - name: Mock BPA Test
        run: |
          pip3 install --upgrade pip
          pip3 install -r mock-bpa-test/requirements.txt
          python3 -m pytest --junitxml=build/default/mock-bpa-test.xml mock-bpa-test || true
      - name: Collect coverage
        run: |
          ./build.sh --target coverage-sonarqube -v
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@c7ee0f9df90b7aa20e8dcf9695dcfe2e7da5b4f2 # v7.2.1
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        with:
          args: >
            --define sonar.cfamily.compile-commands=build/default/compile_commands.json
            --define sonar.junit.reportsPath=build/default/testresults.xml
            --define sonar.python.xunit.reportPath=build/default/mock-bpa-test.xml
            --define sonar.coverageReportPaths=build/default/coverage-sonarqube.xml
